// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/fix/fix.proto

package fix

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FixService_Fix_FullMethodName = "/fix.FixService/Fix"
)

// FixServiceClient is the client API for FixService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FixServiceClient interface {
	Fix(ctx context.Context, in *FixRequest, opts ...grpc.CallOption) (*FixResponse, error)
}

type fixServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFixServiceClient(cc grpc.ClientConnInterface) FixServiceClient {
	return &fixServiceClient{cc}
}

func (c *fixServiceClient) Fix(ctx context.Context, in *FixRequest, opts ...grpc.CallOption) (*FixResponse, error) {
	out := new(FixResponse)
	err := c.cc.Invoke(ctx, FixService_Fix_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FixServiceServer is the server API for FixService service.
// All implementations must embed UnimplementedFixServiceServer
// for forward compatibility
type FixServiceServer interface {
	Fix(context.Context, *FixRequest) (*FixResponse, error)
	mustEmbedUnimplementedFixServiceServer()
}

// UnimplementedFixServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFixServiceServer struct {
}

func (UnimplementedFixServiceServer) Fix(context.Context, *FixRequest) (*FixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fix not implemented")
}
func (UnimplementedFixServiceServer) mustEmbedUnimplementedFixServiceServer() {}

// UnsafeFixServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FixServiceServer will
// result in compilation errors.
type UnsafeFixServiceServer interface {
	mustEmbedUnimplementedFixServiceServer()
}

func RegisterFixServiceServer(s grpc.ServiceRegistrar, srv FixServiceServer) {
	s.RegisterService(&FixService_ServiceDesc, srv)
}

func _FixService_Fix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixServiceServer).Fix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FixService_Fix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixServiceServer).Fix(ctx, req.(*FixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FixService_ServiceDesc is the grpc.ServiceDesc for FixService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FixService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fix.FixService",
	HandlerType: (*FixServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fix",
			Handler:    _FixService_Fix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fix/fix.proto",
}
