[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
user=root

[program:redpolitika]
command=/usr/local/bin/redpolitika
environment=PORT="8081"
user=root
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=30
stopsignal=SIGTERM

[program:nextjs]
command=node server.js
directory=/nextjs
environment=HOSTNAME="0.0.0.0",PORT="3000"
user=root
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=10
stopsignal=SIGTERM

[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile
user=root
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=10
stopsignal=SIGTERM
