// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/detect/detect.proto

package detect

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DetectService_Detect_FullMethodName = "/detect.DetectService/Detect"
)

// DetectServiceClient is the client API for DetectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectServiceClient interface {
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
}

type detectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectServiceClient(cc grpc.ClientConnInterface) DetectServiceClient {
	return &detectServiceClient{cc}
}

func (c *detectServiceClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, DetectService_Detect_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectServiceServer is the server API for DetectService service.
// All implementations must embed UnimplementedDetectServiceServer
// for forward compatibility
type DetectServiceServer interface {
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	mustEmbedUnimplementedDetectServiceServer()
}

// UnimplementedDetectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDetectServiceServer struct {
}

func (UnimplementedDetectServiceServer) Detect(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedDetectServiceServer) mustEmbedUnimplementedDetectServiceServer() {}

// UnsafeDetectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectServiceServer will
// result in compilation errors.
type UnsafeDetectServiceServer interface {
	mustEmbedUnimplementedDetectServiceServer()
}

func RegisterDetectServiceServer(s grpc.ServiceRegistrar, srv DetectServiceServer) {
	s.RegisterService(&DetectService_ServiceDesc, srv)
}

func _DetectService_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectServiceServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectService_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectServiceServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectService_ServiceDesc is the grpc.ServiceDesc for DetectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "detect.DetectService",
	HandlerType: (*DetectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _DetectService_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/detect/detect.proto",
}
