// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/migrator/migrator.proto

package migrator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MigratorService_Migrate_FullMethodName = "/migrator.MigratorService/Migrate"
)

// MigratorServiceClient is the client API for MigratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigratorServiceClient interface {
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error)
}

type migratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMigratorServiceClient(cc grpc.ClientConnInterface) MigratorServiceClient {
	return &migratorServiceClient{cc}
}

func (c *migratorServiceClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error) {
	out := new(MigrateResponse)
	err := c.cc.Invoke(ctx, MigratorService_Migrate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigratorServiceServer is the server API for MigratorService service.
// All implementations must embed UnimplementedMigratorServiceServer
// for forward compatibility
type MigratorServiceServer interface {
	Migrate(context.Context, *MigrateRequest) (*MigrateResponse, error)
	mustEmbedUnimplementedMigratorServiceServer()
}

// UnimplementedMigratorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMigratorServiceServer struct {
}

func (UnimplementedMigratorServiceServer) Migrate(context.Context, *MigrateRequest) (*MigrateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedMigratorServiceServer) mustEmbedUnimplementedMigratorServiceServer() {}

// UnsafeMigratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigratorServiceServer will
// result in compilation errors.
type UnsafeMigratorServiceServer interface {
	mustEmbedUnimplementedMigratorServiceServer()
}

func RegisterMigratorServiceServer(s grpc.ServiceRegistrar, srv MigratorServiceServer) {
	s.RegisterService(&MigratorService_ServiceDesc, srv)
}

func _MigratorService_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServiceServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigratorService_Migrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServiceServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MigratorService_ServiceDesc is the grpc.ServiceDesc for MigratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MigratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "migrator.MigratorService",
	HandlerType: (*MigratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Migrate",
			Handler:    _MigratorService_Migrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/migrator/migrator.proto",
}
