// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/identity/identity.proto

package identity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PluginIdentity_GetCapabilities_FullMethodName = "/identity.PluginIdentity/GetCapabilities"
)

// PluginIdentityClient is the client API for PluginIdentity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginIdentityClient interface {
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
}

type pluginIdentityClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginIdentityClient(cc grpc.ClientConnInterface) PluginIdentityClient {
	return &pluginIdentityClient{cc}
}

func (c *pluginIdentityClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, PluginIdentity_GetCapabilities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginIdentityServer is the server API for PluginIdentity service.
// All implementations must embed UnimplementedPluginIdentityServer
// for forward compatibility
type PluginIdentityServer interface {
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	mustEmbedUnimplementedPluginIdentityServer()
}

// UnimplementedPluginIdentityServer must be embedded to have forward compatible implementations.
type UnimplementedPluginIdentityServer struct {
}

func (UnimplementedPluginIdentityServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedPluginIdentityServer) mustEmbedUnimplementedPluginIdentityServer() {}

// UnsafePluginIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginIdentityServer will
// result in compilation errors.
type UnsafePluginIdentityServer interface {
	mustEmbedUnimplementedPluginIdentityServer()
}

func RegisterPluginIdentityServer(s grpc.ServiceRegistrar, srv PluginIdentityServer) {
	s.RegisterService(&PluginIdentity_ServiceDesc, srv)
}

func _PluginIdentity_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginIdentityServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginIdentity_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginIdentityServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginIdentity_ServiceDesc is the grpc.ServiceDesc for PluginIdentity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginIdentity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.PluginIdentity",
	HandlerType: (*PluginIdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _PluginIdentity_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/identity/identity.proto",
}
